apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-videos-deployment
spec:
  selector:
    matchLabels:
      app: api-videos-pod
  template:
    metadata:
      labels:
        app: api-videos-pod
    spec:
      containers:
        - name: api-videos-container
          image: # valor será incluido no pipeline
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: videos-db-connection-secret
                  key: connection-string
            - name: AWS__Credentials__AccessKey
              valueFrom:
                secretKeyRef:
                  name: aws-credential-secret
                  key: access-key
            - name: AWS__Credentials__SecretKey
              valueFrom:
                secretKeyRef:
                  name: aws-credential-secret
                  key: secret-key
            - name: AWS__Credentials__SessionToken
              valueFrom:
                secretKeyRef:
                  name: aws-credential-secret
                  key: session-token
            - name: AWS__Region
              valueFrom:
                secretKeyRef:
                  name: aws-credential-secret
                  key: region
            - name: AWS__CloudFileStorage__ContainerName
              valueFrom:
                configMapKeyRef:
                  name: api-videos-configmap
                  key: bucket-name
            - name: AWS__CloudFileStorage__TimeoutDuration
              valueFrom:
                configMapKeyRef:
                  name: api-videos-configmap
                  key: timeout-default

          resources:
            requests:
              memory: "96Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
