name: snacktech-vidsnap

services:
  sql-db:
    container_name: snacktech-vidsnap-database
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04    
    restart: always
    networks:
      - snacktech-vidsnap-net
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: <informe aqui>
    ports:
      - 1433:1433 #TODO: talvez remover isso antes de entregar, para que nao seja possivel acessar o banco sem ser pela aplicacao
    volumes:
      - sql-db-volume:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P <informe aqui> -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  vidsnap.api:
    container_name: snacktech-vidsnap-web-api
    image: snacktech-vidsnap-api:alpha
    build:
      context: .
      dockerfile: Driving/Vidsnap.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - AWS_ACCESS_KEY_ID=<informe-aqui>
      - AWS_SECRET_ACCESS_KEY=<informe-aqui>
      - AWS_SESSION_TOKEN=<informe-aqui>
      - AWS_REGION=us-east-1
      - AWS__CloudFileStorage__ContainerName=vidsnap-video-upload
      - AWS__CloudFileStorage__TimeoutDuration=1
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    networks:
      - snacktech-vidsnap-net
    depends_on:
      sql-db:
        condition: service_healthy

  vidsnap.worker.atualizastatusprocessamento:
    image: snacktech-vidsnap-worker-atualiza-status-processamento:alpha
    build:
      context: .
      dockerfile: Driving/Vidsnap.Worker.AtualizaStatus/Vidsnap.Worker.AtualizaStatusProcessamento/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AWS__Credentials__AccessKey=[SEU-ACCESS-KEY-AQUI]
      - AWS__Credentials__SecretKey=[SEU-SECRET-KEY-AQUI]
      - AWS__Credentials__SessionToken=[SEU-SESSION-TOKEN-AQUI]
      - AWS_REGION=us-east-1
      - AWS__Queues__MaxNumberOfMessages=5
      - AWS__Queues__QueueURL=https://sqs.us-east-1.amazonaws.com/<informe-aqui>/vidsnap-atualiza-video-status
      - AWS__Queues__DlqQueueURL=https://sqs.us-east-1.amazonaws.com/<informe-aqui>/vidsnap-atualiza-video-status-dlq
    restart: on-failure
    networks:
      - snacktech-vidsnap-net
    depends_on:
      sql-db:
        condition: service_healthy

volumes:
  sql-db-volume: {}

networks:
  snacktech-vidsnap-net:
    driver: bridge
